### ISSUE TITLE
Weight can be max 1.0 and min 0

### ISSUE THREAD

**Issue by bobvanluijt** [creativesoftwarefdn/weaviate#554]
When creating things or actions, a weight can be maximal `1.0` and minimal `0.0`.

# Background

In the contextionary's vector space a polygon will be created of the keywords. The weights will determine where the new vector points are created.

For example with two keywords and a class all with a weight of 1, the centroid will be placed in the center, if one keyword should be _less_ important, the weight can be lowered. There _might_ be the possibility that we want to have `>1.0` in the future but I don't foresee this.

# Suggested implementations

1. Make it a configuration flag that defaults to _not allowing `>1.0` weights`_. Or;
2. Make it an error or warning if a weight is set to `>1.0`. Or;
3. If a weight is `>1.0` set it to `1.0`.

**Comment by moretea** [comment]
How does it matter if a user sets a higher weight than 1? Maybe they want to use a total of 60 sum, and use chunks of 20 for each keyword. 60 is a very nice number to divide into different parts.
That is the exactly as setting the weight for each keyword to 0.3333.
There is nothing magical about a maximum of 1 IMHO.

We could require that the total _sum_ of the weights should be 1.0 (with a certain epsilon). That would make sense to me; you'd basically force users to write down a percentage. Adding a keyword will require you to take some of the weight of another.

In this latter approach, instead of making the pie bigger, you need to cut pieces smaller if you want to have more pieces.

**Comment by moretea** [comment]
Also this is not part of milestone A IMHO; this will only become relevant once you start to implement fuzzy searches/network queries.

**Comment by etiennedi** [comment]
#645 adds the validation as proposed in suggestion 2 for querying for weights. We could should add the same for imports. I wasn't previously aware of this issue, but it's very much connected to #645 - maybe I can solve it as part of that, too.

**Comment by etiennedi** [comment]
FYI: Hasn't been tackled as part of #645 because that issue was already very big on its own, so we need to keep this open.
