### ISSUE TITLE
Add HTTP responses for errors from endpoints that now have grown a synchronous option

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#617]

**Comment by moretea** [comment]
Grep source for gh-617

**Comment by etiennedi** [comment]
Added the "Bad UX" label, because currently when a db request fails, the user doesn't get any resonse at all. Instead we panic and never return the request, i.e. the user gets something like EOF.

Example: 
![image](https://user-images.githubusercontent.com/8974479/50966474-4e8d8d80-14d5-11e9-9fc8-9e1442619975.png)

All the user will see is something like `(*url.Error)(0xc0005022a0)(Post http://localhost:8080/weaviate/v1/actions: EOF)`
