### ISSUE TITLE
Update 'magic' words in contextionary after schema is updated

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#618]

**Comment by moretea** [comment]
Grep source on gh-618

**Comment by bobvanluijt** [comment]
Hi @moretea, can you please elaborate a bit more on what this issue entails?

**Comment by etiennedi** [comment]
@bobvanluijt I did some digging as part of #645 and I think I understand what this issue is about:

## Background
@moretea has build some code that extends the contextionary (as we read it from the file) based on the current schema.

* The added items have the format`$kind[className]`, e.g. `$thing[City]` 
* If a class has keywords specified, the code calculates the weighted centroids from keywords only (ignoring the className)
* If a class has no keywords, the className is split up by camelCase (e.g. `AirplaneHangar` becomes `Airplane` and `Hangar`). They are then treated as equally weighted parts
* The same is done for properties in the format `$className[propertyName]`, e.g. `$City[population]`

## This issue
Now this issue is about actually using the code. The code is currently not in use. I assume this is because the code to do so, has to run on every schema update, so it was probably removed when the "dynamic schemas via API" feature was introduced.

Most likely we will have to take care of this as part of #645 as well.

**Comment by bobvanluijt** [comment]
I see @etiennedi, what is important is that camel case plays an important role in keyword and class name definition, this is outlined [here](https://github.com/creativesoftwarefdn/weaviate/blob/develop/docs/en/use/ontology-schema.md#CamelCase).

**Comment by etiennedi** [comment]
Thanks, @bobvanluijt, I've included that info into the task list in #645. Closing here, since there's now some duplication.

**Comment by etiennedi** [comment]
As planned, this was tackled in #645 and will be included if the respective PR is merged.
