### ISSUE TITLE
Feature flag location for Monitoring Service

### ISSUE THREAD

**Issue by JeroenStravers1** [creativesoftwarefdn/weaviate#726]
### Issue
I put the monitoring service feature flag in `tools/dev/conf.json` and I'm encountering an "issue" in the way reading the config file is handled (it's not wrong, it just doesn't suit my needs). 

Really short version: the config (and thereby my flag) is only accessible at runtime as which config environment is chosen relies on command line args. Since all monitoring functions check the state of the flag this effectively precludes the use of unit tests for the monitoring service; I'd need a running Weaviate instance.

### Options
I can't find another logical spot for config items in our codebase, so I see two options:
- all my tests will be acceptance tests. At over 10 mins per test run this does not seem optimal.
- I find a new place for the flag. I'd suggest putting the flag conf file in the monitoring folder. 
This means deviating from the provided location (the json conf), which is why I don't want to just unilaterally decide.

The location will of course be documented. 

### Current solution
I'm using basic [constants](https://github.com/creativesoftwarefdn/weaviate/blob/feature/monitoring-service/telemetry/utils/toggle.go) as an intermediate solution.

Thoughts @etiennedi @bobvanluijt?

Related to #699

**Comment by etiennedi** [comment]
> * all my tests will be acceptance tests. At over 10 mins per test run this does not seem optimal.
No, there has to be a better way :)

Most likely this can be solved with a fake for the config. Let's say you have a root type like this

```go
type Monitoring struct {}
```

your type depends on the config being present so let's add it as a field
```go
type Monitoring struct {
  config *config.WeaviateConfig
}
```

Let's say you also have a constructor function to assert that your Monitoring type can never be created without the required deps:

```go
func New(cfg *config.WeaviateConfig) *Monitoring {
  return &Monitoring {
    config: cfg,
  }
}
```

Now you can use your constructur with the actual config object at runtime, i.e. somewhere in the `restapi` package, which is effectively our main package, you can simply do

```go
monitoring := monitoring.New(serverConfig)
```

However, in the tests you can just create whatever config you want, like so:

```go
testConfig := &config.WeaviateConfig{
  /* ignore the fields your type doesn't care about */
  Monitoring: &config.MontoringConfig{
    Enabled: true, // or false, whichever you want to test
    Endpoint: "http://foo.bar" // you could even create an *httptest.Server and use the .URL of it if you want to :)
  }
}
```

One special note about this line:
```go
  Monitoring: &config.MontoringConfig{
```
I haven't looked at the current structure of the `config` package. It might be that that's the wrong place for your new config object. Maybe it should just be with the rest of your monitoring types. Not sure, feel free to place it where it makes sense.

Does this help?

**Comment by JeroenStravers1** [comment]
This helps very much, thank you!

**Comment by etiennedi** [comment]
Some more background on how I got to the above solution: Effectively this is a classicist vs mockist problem (for testing there's always a suiting [Martin Fowler article](https://martinfowler.com/articles/practical-test-pyramid.html#SociableAndSolitary) somewhere ;) )

By writing the stuff in the file you'd basically need the classicist way of unit testing, i.e. you'd need to process the file from disk, run part of the startup routine until you get to your Monitoring unit and then have access to the config.

By outlining the solution above, I've basically made an implicit decision to go for a Mockist approach. I.e. I want to test your new unit in isolation, I don't care how the config got from the file to your unit. I assume - because of Go's strong type system and other parts of the app which are tested - that by the time the config has made it to your unit it will be guaranteed to have a the desired format. This way we control the outcome of the "config reading process", but have abstracted the "how is the config being read" part completely away.

**Comment by etiennedi** [comment]
One more note:

This bit is oversimplified:
```go
testConfig := &config.WeaviateConfig{
  Monitoring: &config.MontoringConfig{
    Enabled: true, 
    Endpoint: "http://foo.bar" 
  }
}
```

In real life the structure would be `WeaviateConfig.Environment.Monitoring`, instead of `WeaviateConfig.Monitoring` but the same principles apply. :)
