### ISSUE TITLE
Docker-compose for "try-out" setup

### ISSUE THREAD

**Issue by bobvanluijt** [creativesoftwarefdn/weaviate#738]
A docker compose setup for a stable and unstable Weaviate with the latest Contextionary.

The goal is that people can try out Weaviate locally.

Also;
- [ ] update docs
- [ ] include Playground(?)

**Comment by etiennedi** [comment]
At first sight, it looks like only etcd is missing. I'll add it and give it a shot.

The goal is that a simple `docker-compose up` is sufficient.

Keep in mind, I think we haven't ever pushed an image tagged with `:stable` though, so until we do that, the `stable` version might fail.

**Comment by etiennedi** [comment]
Just pushed it,

the `unstable` should work now. As outlined above, `stable` should fail because no such image exists.

Additionally please keep in mind:

1.) while a simple `docker-compose up` works, it blocks the terminal, because it attaches to the logs of all containers (including janus, cassandra and elastic). This is very verbose. So I'd instead recommend to run `docker-compose up -d` to be detached from the logs. You can always still re-attach to the logs of individual containers using `docker-compose logs -f weaviate` (to attach to the weaviate container)

2.) The image we have currently tagged as `unstable` is extremly verbose because I used this for testing on Kubernetes. If you like I can try to clean this verbosity up and push a new one. (@bobvanluijt)

**Comment by bobvanluijt** [comment]
Thanks @etiennedi, I'll assign to myself

**Comment by bobvanluijt** [comment]
@etiennedi this is obsolete now?

**Comment by etiennedi** [comment]
It's already closed. What do you mean?

**Comment by bobvanluijt** [comment]
Sorry, responded directly via email, please ignore.

**Comment by etiennedi** [comment]
Roger that. Actively ignoring.
