### ISSUE TITLE
Implement monitoring function call logging

### ISSUE THREAD

**Issue by JeroenStravers1** [creativesoftwarefdn/weaviate#767]
## Background
I need to implement GQL function call logging as part of the monitoring service. This goes two levels deep, so local/network and then get/getmeta/aggregate/fetch/introspect. I need to log a separate call per aggregate function used, so as far as I can tell logging needs to happen at resolver level.

## Issue
I've declared a [logging variable](https://github.com/creativesoftwarefdn/weaviate/blob/3853066f381dfafd92beabc3f26c576d58516849/restapi/configure_weaviate.go#L100) and can get that to the GraphQL struct by passing it along, but I don't see a good way to make the log reachable from the resolvers themselves. Any thoughts on this matter?

@etiennedi 

Related: #699

**Comment by etiennedi** [comment]
I'll outline the example of how we get the contextionary to the resolver for `Local { Fetch }` as this should essentially be the same flow.

One note before: It is very important (to avoid bad coupling and circular imports) to decouple this as much as possible. This means that from the perspective of the `graphqlapi` package the type you accept is an interface that is declared within the grahpql package. Otherwise it will become almost impossible to test the `graphql` package in isolation. Whereas with the locally owned interface (that only contains the methods you actually call) you can very easily create a drop-in fake/stub/mock for your tests.

So, coming back to the contextionary example, here's what we do:

## In the `restapi` package

The contextionary is also defined as a global var in the `restapi` package. (I have plans to group all those dependencies together, see #723, but I'll ignore that for now for the sake of simplicity):
https://github.com/creativesoftwarefdn/weaviate/blob/bbb785645537667d909a19bc1942029a4d7eef70/restapi/configure_weaviate.go#L88

There's also a helper type to group everything we want to make available at GraphQL resolve time. You could easily add your type to this:
https://github.com/creativesoftwarefdn/weaviate/blob/bbb785645537667d909a19bc1942029a4d7eef70/restapi/configure_weaviate.go#L102-L106

This type also has a helper method to retrieve the contextionary again. This is very helpful since we can easily replace this part of the helper struct with a fake (in tests in the `graphqlapi` package): 
https://github.com/creativesoftwarefdn/weaviate/blob/bbb785645537667d909a19bc1942029a4d7eef70/restapi/configure_weaviate.go#L112-L114

We are using the above helper type whenever we rebuild the graphQL structure (i.e. on schema or peer changes) like so:
https://github.com/creativesoftwarefdn/weaviate/blob/bbb785645537667d909a19bc1942029a4d7eef70/restapi/configure_weaviate.go#L750-L769
*Note the lines in the center that create the type and pass it on:*
https://github.com/creativesoftwarefdn/weaviate/blob/bbb785645537667d909a19bc1942029a4d7eef70/restapi/configure_weaviate.go#L759-L760

## In the `graphqlapi` package and its subpackages

From the perspective of the `graphqlapi` package, the helper type (which is never explicitly mentioned) acts as something implementing the `ResolverProviderInterface`. Note the method `GetContextionary` which returns another interface that is local to the `graphqlapi/local/fetch` package:
https://github.com/creativesoftwarefdn/weaviate/blob/bbb785645537667d909a19bc1942029a4d7eef70/graphqlapi/resolver.go#L35-L51

If we jump into the `graphqlapi/local/fetch` package we find the defintion of that interface. Note that it only contains a very small subset of all the methods the "real" contextionary has. I only want to use a single one, so I'm also only "requiring" one. (Think of the interface as a message to outside providers that says "I need a type that has at least this method. It can have more that that, but to do my job I really only care about this single method": https://github.com/creativesoftwarefdn/weaviate/blob/bbb785645537667d909a19bc1942029a4d7eef70/graphqlapi/local/fetch/resolver.go#L31-L35

The resolver itselfs then calls a small helper method to get to the contextionary:
https://github.com/creativesoftwarefdn/weaviate/blob/bbb785645537667d909a19bc1942029a4d7eef70/graphqlapi/local/fetch/resolver.go#L63-L66

In there we are asserting that the contextionary is actually present in the `Source` of the resolver arguments. The source is a map and we want to check whether the map has a key `Contextionary` that implements our interface):
https://github.com/creativesoftwarefdn/weaviate/blob/bbb785645537667d909a19bc1942029a4d7eef70/graphqlapi/local/fetch/resolver.go#L123-L126

So how did the `"Contextionary"` key get into this map? In the `graphqlapi` package on the `graphQL.Resolve()` method, which is called for every incoming grahpql request we extracted the contents of the helper type from the `restapi` package and inserted them into the map:
https://github.com/creativesoftwarefdn/weaviate/blob/bbb785645537667d909a19bc1942029a4d7eef70/graphqlapi/schema.go#L56-L84
*Note: In order for this object to actually "arrive" at your desired resolver, all resolvers between the root and your target resolver must actually bubble up this object*.

I think you can use this exact same flow for your type as well. Does this help? Any other questions?

**Comment by JeroenStravers1** [comment]
This does look like the solution I was looking for, thanks!

**Comment by etiennedi** [comment]
Awesome, happy to hear this.
